// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { config, library, dom } from '@fortawesome/fontawesome-svg-core'

// Fix flicker with Turbolinks (https://fontawesome.com/how-to-use/on-the-web/using-with/turbolinks)
config.mutateApproach = 'sync'

import { faCheck as faCheckSolid } from '@fortawesome/pro-solid-svg-icons/faCheck'
import { faTimes as faTimesSolid } from '@fortawesome/pro-solid-svg-icons/faTimes'

library.add(
  faCheckSolid,
  faTimesSolid
);

dom.watch();